force-exclude = true
line-length = 99
required-version = ">=0.15.0"
output-format = "concise"

lint.ignore = ["E501"]

# rules: https://beta.ruff.rs/docs/rules
lint.select = [
    "A",      # flake8-builtins
    "ANN",    # flake8-annotations
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "C90",    # mccabe (complexity)
    "E",      # pycodestyle error
    "ERA",    # eradicate (commented-out code)
    "EXE",    # flake8-executable
    "F",      # pyflakes
    "FBT",    # flake8-boolean-trap
    "FURB",   # refurb
    "G",      # flake8-logging-format
    "I",      # isort
    "ISC",    # flake8-implicit-str-concat
    "N",      # pep8-naming
    "PGH004", # disallow blanket noqa
    "PIE",    # flake8-pie
    "PL",     # pylint
    "PT",     # flake8-pytest-style
    "PTH",    # flake8-use-pathlib
    "Q",      # flake8-quotes
    "RET",    # flake8-return
    "RUF",    # Ruff-specific rules
    "S108",   # flake8-bandit: hardcoded temp file/directory paths
    "SIM",    # flake8-simplify
    "TID",    # flake8-tidy-imports
    "TRY003", # raise-vanilla-args
    "UP",     # pyupgrade
    "W",      # pycodestyle warning
]


lint.per-file-ignores."src/repoactive/cli.py" = [
    "FBT", # Typer requires boolean default parameters for flags
]

lint.mccabe.max-complexity = 10
lint.flake8-tidy-imports.ban-relative-imports = "all"
