[global]
excludes = ["uv.lock", "LICENSE"]

[formatter.ruff-check]
command = "uv"
options = ["run", "ruff", "check", "--fix"]
includes = ["*.py"]
priority = 1

[formatter.ruff-format]
command = "uv"
options = ["run", "ruff", "format"]
includes = ["*.py"]
priority = 2

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh", "*.bash"]
priority = 1

[formatter.shfmt]
command = "shfmt"
options = ["-w", "-i", "4"]
includes = ["*.sh", "*.bash"]
priority = 2

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md"]
